### ISSUE TITLE
SSL certs expired or invalid for curl requests

### ISSUE THREAD

**Issue by xmtbiker** [WireGuard/wireguard-vyatta-ubnt#154]
### Package version

e50-v1-v1. O .20220627 -VI . O . 20210914 . deb

### Firmware version

1.10.11

### Device

EdgeRouter X (SFP, 10 X, EP-R6) - e50

### Issue description

When running on an ERX using this code the script shows an error due to invalid SSL cert. 
 `curl  -sSL  https://github.com/mafredri/vyatta-wireguard-installer/raw/master/wireguard.sh  -o /config/scripts/post-config.d/wireguard.sh; chmod +x /config/scripts/post-config.d/wireguard.sh; cd /; cd /config/scripts/post-config.d; ./wireguard.sh install; cd ~
`

When you run the code with -k or --insecure the package downloads but the curl requests from inside the script fail due to invalid SSL. I was able to edit the curl commands within the script to also use -k but that was only a temp workaround. Would be very useful for the issue to be resolved as I use this on a regular basis. THANKS!

**Comment by FossoresLP** [comment]
Hi @xmtbiker,

Please note that we do not support third-party installation scripts.

Downloads are handled via GitHub releases and I've verified that the certificates are valid.

If downloading the package via the link in the [Wiki](https://github.com/WireGuard/wireguard-vyatta-ubnt/wiki/EdgeOS-and-Unifi-Gateway) fails, please ensure you are running the most recent firmware release to ensure the included certificate authorities are up-to-date.
In case this still fails on up-to-date firmware following the instructions in the Wiki, please download the deb file on your computer and transfer it using `scp` instead.

Since Ubiquiti has only released hotfixes for a while for EdgeOS, new certificate authorities might not be available on the devices. This is not something we can resolve. A new release of EdgeOS is in development that should fix any such issues in case they exist.
