### ISSUE TITLE
No new version since Jul 2, 2022

### ISSUE THREAD

**Issue by azagramac** [WireGuard/wireguard-vyatta-ubnt#156]
Describe the feature you would like to request in as much detail as possible.

The current version is
Jul 2, 2022
Module	1.0.20220627
Tools	1.0.20210914

there are no new wireguard updates as of today?

If it is specific to certain devices please let us know which.

**Comment by FossoresLP** [comment]
Hi @azagramac,
thank you for bringing this up.
Due to very limited updates from Ubiquiti over the last couple of years, the module is still compatible with the latest kernel versions for EdgeOS 1 and 2. Should this change, new builds will be created.
Wireguard itself has had no updates to its out-of-tree kernel module or tools since 2022.
