### ISSUE TITLE
UGW firmware 4.4.51

### ISSUE THREAD

**Issue by maletazul** [WireGuard/wireguard-vyatta-ubnt#48]
Hi Team,

anyone test USG3 or USG4P with this firmware?

UGW firmware | 4.4.51

**Comment by FossoresLP** [comment]
Hi @maletazul,

since the 4.4.51 release only contains a few bugfixes (and no kernel update) you should be able to use this package without issues even though it was built for 4.4.50.

**Comment by maletazul** [comment]
well thats the problem, 
i´m getting handshake problems, on the client side i have rx:0 , and i get only tx trafic, its seams the WAN rule and not passing trafic, or wireguard are not working correctly.
The json are very clean, so just why i ask if someone are using this firmware, because are not official documented in this release.

**Comment by maletazul** [comment]
Just to confirm it works on usg3p and usg4p in firmware 4.4.51

**Comment by ShawnDordeJay** [comment]
@maletazul I have the same problem. How did you fix?

**Comment by maletazul** [comment]
@ShawnDordeJay it was configurations mistakes, double check all

**Comment by juliaanduchateau** [comment]
Hi,
I'm running V4.4.51.5287926 on a USG3 and when trying to install, I get the following error:

dpkg-deb: error: `ugw3-v1-v1.0.20200908-v1.0.20200827.deb' is not a debian format archive
dpkg: error processing ugw3-v1-v1.0.20200908-v1.0.20200827.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 ugw3-v1-v1.0.20200908-v1.0.20200827.deb

**Comment by FossoresLP** [comment]
@juliaanduchateau Your issue seems to be a completely separate problem that should normally be handled in a new issue.
However this might be a very simple thing so please first try these steps:
- Re-download the package
- Use `wget` or `curl -L` to follow links (GitHub uses redirects)
- Verify the package size corresponds to the size listed on GitHub

If you are still experiencing issues, please go ahead and open a new issue.
