### ISSUE TITLE
Package wg-quick

### ISSUE THREAD

**Issue by samip5** [WireGuard/wireguard-vyatta-ubnt#54]
I would request to also include wg-quick utility in this.

**Comment by FossoresLP** [comment]
Hi @samip5,
wg-quick is currently not included because it would conflict with the intended configuration mechanism of this package.
I would consider it's use strongly discouraged and unsupported on EdgeOS.
You can always add wg-quick very easily yourself as it is a simple script you can copy from the official repository.

**Comment by samip5** [comment]
Can you please explain how can I do equilevant config to this wg-quick config?
I need to be able to set the actual peer address for it.

```
[Interface]
PrivateKey = <snip>
# PublicKey = KGz965B7iQWUa9lgDU+ocUoWP9pBWE+Tm/7uiq7iVHY=
Address = 172.22.114.97/32,fe80::21b:42ff:42bb:2db0/64
PostUp = /usr/sbin/ip addr del dev no_trd_burble 172.22.114.97/32 && /sbin/ip addr add dev no_trd_burble 172.22.114.97/32 peer 172.20.129.185/32
PostUp = /usr/sbin/ip addr del dev no_trd_burble fe80::21b:42ff:42bb:2db0/64 && /sbin/ip addr add dev no_trd_burble fe80::21b:42ff:42bb:2db0/128 peer fe80::42:2601:39:1/64
ListenPort = 52601
Table = off

[Peer]
PublicKey = PC0ZAVLrmbbgPRkcbUry4vFKbo6uWdFdL4gTrxE1sTY=
Endpoint = <snip>
PersistentKeepalive = 560
AllowedIPs = 172.16.0.0/12, 10.0.0.0/8, fd00::/8, fe80::/10

**Comment by FossoresLP** [comment]
You can set post-up scripts using `up-command`.
For details take a look at the following commit: 3f3aa6e
